/** 形象類 10 套：企業／公司官網、產品登陸頁 */
import type { SiteTemplate } from '../common';
import { MENU, PAGES } from '../common';

const nav = (extra: { label: string; href: string }[] = []) => [{ label: '首頁', href: '/' }, ...extra, { label: '關於我們', href: '/p/about' }, { label: '聯絡我們', href: '/p/contact' }];
const about = (title = '關於我們'): SiteTemplate['pages'][number] => ({ slug: 'about', title, sections: [{ kind: 'hero', variant: 'center', title, subtitle: '一段話說清楚我們是誰、為誰而做', compact: true }, { kind: 'split', title: '我們的故事', text: '從一個想法開始，到今天服務上百位客戶。這裡放品牌起源、轉折與現在的樣子，三段以內。', imageSide: 'left' }, { kind: 'stats', variant: 'cards', items: [{ value: '10+', label: '年經驗' }, { value: '300+', label: '合作客戶' }, { value: '98%', label: '回購／續約率' }] }, { kind: 'team', variant: 'grid', title: '核心團隊', members: [{ name: '創辦人', role: '執行長', bio: '一句話介紹' }, { name: '夥伴', role: '營運長', bio: '一句話介紹' }, { name: '夥伴', role: '設計總監', bio: '一句話介紹' }] }, { kind: 'cta', variant: 'band', title: '想更了解我們？', buttonText: '聯絡我們', buttonHref: '/p/contact' }] });

export const IMAGE_TEMPLATES: SiteTemplate[] = [
  {
    id: 'image-corporate-classic', category: 'image', name: '企業官網', style: '經典', tagline: '服務四卡＋數字＋流程＋客戶牆，最穩的公司門面', tags: ['公司', 'B2B', '服務業'], source: 'Wix 商業類高頻骨架',
    theme: { mode: 'light', accent: '#0b6e77', font: 'sans', radius: 'md', header: 'solid', footer: 'columns' },
    menu: { header: nav([{ label: '服務項目', href: '/p/services' }, { label: '最新消息', href: '/blog' }]), footer: MENU.footerBasic },
    home: [
      { kind: 'hero', variant: 'split', kicker: '專業 · 可靠 · 有溫度', title: '把複雜的事，做成你放心的樣子', subtitle: '一句話說明你解決什麼問題、為誰解決。', ctaText: '了解服務', ctaHref: '/p/services', cta2Text: '聯絡我們', cta2Href: '/p/contact' },
      { kind: 'features', variant: 'grid', title: '我們的服務', columns: 4, items: [{ icon: '🧭', title: '策略規劃', text: '先把目標與路徑釐清。' }, { icon: '🛠️', title: '執行落地', text: '有節奏地把事做完。' }, { icon: '📈', title: '成效追蹤', text: '用數字說話。' }, { icon: '🤝', title: '長期陪伴', text: '上線後才是開始。' }] },
      { kind: 'stats', variant: 'row', items: [{ value: '12', label: '年產業經驗' }, { value: '350+', label: '完成專案' }, { value: '4.9', label: '客戶評分' }, { value: '24h', label: '回覆時間' }] },
      { kind: 'split', title: '為什麼選擇我們', text: '三個具體理由，各一句。避免形容詞，寫做法與結果。', bullets: ['專責窗口全程對接', '透明報價，沒有隱藏費用', '交付後 30 天免費調整'], ctaText: '看合作流程', ctaHref: '#process' },
      { kind: 'steps', id: 'process', variant: 'numbers', title: '合作流程', items: [{ title: '需求訪談', text: '30 分鐘釐清目標。' }, { title: '提案報價', text: '一次列清項目與時程。' }, { title: '執行交付', text: '每週進度回報。' }, { title: '上線維護', text: '持續優化。' }] },
      { kind: 'logos', title: '合作夥伴', items: [{ name: '客戶 A' }, { name: '客戶 B' }, { name: '客戶 C' }, { name: '客戶 D' }, { name: '客戶 E' }, { name: '客戶 F' }] },
      { kind: 'posts', variant: 'grid', title: '最新消息', limit: 3 },
      { kind: 'cta', variant: 'band', title: '準備好開始了嗎？', text: '留下需求，一個工作天內回覆。', buttonText: '免費諮詢', buttonHref: '/p/contact' },
    ],
    pages: [about(), { slug: 'services', title: '服務項目', sections: [{ kind: 'hero', variant: 'center', title: '服務項目', subtitle: '依需求挑選，或讓我們幫你組合', compact: true }, { kind: 'features', variant: 'list', items: [{ title: '服務一', text: '做什麼、適合誰、多久交付。' }, { title: '服務二', text: '做什麼、適合誰、多久交付。' }, { title: '服務三', text: '做什麼、適合誰、多久交付。' }] }, { kind: 'faq', title: '常見問題', items: [{ q: '費用怎麼算？', a: '依項目與範圍報價，報價單一次列清。' }, { q: '多久可以完成？', a: '一般專案 4 到 8 週。' }] }, { kind: 'cta', variant: 'card', title: '想討論你的需求？', buttonText: '聯絡我們', buttonHref: '/p/contact' }] }, PAGES.contact()],
  },
  {
    id: 'image-manifesto-dark', category: 'image', name: '宣言式官網', style: '編輯 · 深色', tagline: '滿版大字宣言、數字證明、案例與見證，像一篇有態度的雜誌', tags: ['行銷', '代理商', '個性'], source: '指定成品站 airuru.cc 骨架',
    theme: { mode: 'dark', accent: '#ff3b30', font: 'display', radius: 'sm', header: 'bar', footer: 'minimal', heading: 'display' },
    menu: { header: [{ label: '我們的服務', href: '/#services' }, { label: '實戰案例', href: '/p/cases' }, { label: '知識庫', href: '/blog' }, { label: '關於我們', href: '/p/about' }, { label: '免費諮詢', href: '/p/contact' }], footer: MENU.footerBasic },
    home: [
      { kind: 'hero', variant: 'cover', kicker: '台灣頂尖團隊', title: '只做有結果的事，\n其餘一律不接。', subtitle: '一句話定義你的標準。', ctaText: '免費諮詢', ctaHref: '/p/contact', tone: 'dark' },
      { kind: 'split', id: 'thesis', title: '流量會漲，生意不一定會。', text: '用兩三段講清楚你的核心觀點，讓對的客戶認同、不對的客戶自己走開。', imageSide: 'right', bullets: ['觀點一：一句話', '觀點二：一句話'], tone: 'dark' },
      { kind: 'stats', variant: 'inline', items: [{ value: '2 億+', label: '累積成效' }, { value: '1 億+', label: '實際變現' }, { value: '1,400+', label: '完成作品' }], tone: 'dark' },
      { kind: 'split', id: 'services', title: '我們的服務', text: '', sticky: true, imageSide: 'left', bullets: ['代營運：企劃到上線一條龍', '保證班：線上學習、線下實作', '企業內訓：為團隊量身訂做', '顧問陪跑：每個關鍵節點的專業指導'], ctaText: '看完整服務', ctaHref: '/p/services', tone: 'dark' },
      { kind: 'stats', variant: 'cards', title: '實戰案例', subtitle: '數據是唯一的語言', items: [{ value: '40,000+', label: '全網粉絲', note: '客戶 A · 零售' }, { value: '4,500 萬', label: '一年變現', note: '客戶 A' }, { value: '300 萬', label: '啟動兩週', note: '客戶 B' }], tone: 'dark' },
      { kind: 'gallery', variant: 'grid', title: '實績戰報', columns: 4, items: [], tone: 'dark' },
      { kind: 'testimonials', variant: 'cards', title: '他們都做到了', items: [{ quote: '一句客戶原話。', name: '客戶 A', role: '零售業' }, { quote: '一句客戶原話。', name: '客戶 B', role: '餐飲業' }, { quote: '一句客戶原話。', name: '客戶 C', role: '教育業' }, { quote: '一句客戶原話。', name: '客戶 D', role: '服務業' }], tone: 'dark' },
      { kind: 'contact', variant: 'cards', title: '你看完了。你的客戶也會。', subtitle: '選一個方式找我們', items: [{ icon: '💬', label: 'LINE', value: '@yourbrand', href: '' }, { icon: '✉️', label: 'Email', value: 'hello@example.com', href: 'mailto:hello@example.com' }, { icon: '📞', label: '電話', value: '02-0000-0000', href: 'tel:+886200000000' }], tone: 'dark' },
    ],
    pages: [
      { slug: 'about', title: '關於我們', sections: [{ kind: 'hero', variant: 'center', title: '關於我們', subtitle: '一群用數據和創意改變品牌的人', compact: true }, { kind: 'team', variant: 'founder', title: '創辦人', members: [{ name: '創辦人', role: '創辦人', bio: '三段以內：為什麼開始、堅持什麼、要帶客戶去哪裡。' }] }, { kind: 'features', variant: 'grid', title: '我們的使命', columns: 3, items: [{ icon: '🎯', title: '使命一', text: '一句話' }, { icon: '⚡', title: '使命二', text: '一句話' }, { icon: '🤝', title: '使命三', text: '一句話' }] }, { kind: 'team', variant: 'grid', title: '專業團隊', members: [{ name: '夥伴', role: '策略' }, { name: '夥伴', role: '製作' }, { name: '夥伴', role: '投放' }] }, { kind: 'cta', variant: 'band', title: '準備好一起創造成績了嗎？', buttonText: '免費諮詢', buttonHref: '/p/contact' }] },
      { slug: 'cases', title: '實戰案例', sections: [{ kind: 'hero', variant: 'center', title: '實戰案例', subtitle: '成果是我們唯一的證明', compact: true }, { kind: 'stats', variant: 'cards', items: [{ value: '40,000+', label: '全網粉絲', note: '客戶 A' }, { value: '4,500 萬', label: '一年變現', note: '客戶 A' }, { value: '300 萬', label: '啟動兩週', note: '客戶 B' }] }, { kind: 'gallery', variant: 'grid', columns: 3, items: [] }, { kind: 'cta', variant: 'band', title: '下一個案例是你', buttonText: '免費諮詢', buttonHref: '/p/contact' }] },
      { slug: 'services', title: '我們的服務', sections: [{ kind: 'hero', variant: 'center', title: '我們的服務', compact: true }, { kind: 'features', variant: 'list', items: [{ icon: '🎬', title: '代營運', text: '企劃、拍攝、剪輯一條龍。' }, { icon: '🏅', title: '保證班', text: '線上學習、線下實作。' }, { icon: '🏢', title: '企業內訓', text: '為團隊量身訂做。' }, { icon: '🚀', title: '顧問陪跑', text: '每個關鍵節點的專業指導。' }] }, { kind: 'cta', variant: 'band', title: '想知道哪個適合你？', buttonText: '免費諮詢', buttonHref: '/p/contact' }] },
      PAGES.contact({ tone: 'dark' }),
    ],
  },
  {
    id: 'image-landing-product', category: 'image', name: '產品登陸頁', style: '簡潔', tagline: '單頁：賣點、好處、見證、方案、FAQ、CTA，一路往下轉換', tags: ['單頁', '登陸頁', 'SaaS'], source: 'Wix 單頁面／登陸頁面骨架',
    theme: { mode: 'light', accent: '#2563eb', font: 'sans', radius: 'xl', header: 'minimal', footer: 'minimal' },
    menu: { header: [{ label: '特色', href: '/#features' }, { label: '方案', href: '/#pricing' }, { label: '常見問題', href: '/#faq' }], footer: MENU.footerBasic },
    home: [
      { kind: 'hero', variant: 'split', kicker: '新上市', title: '一句話講清楚產品帶來的改變', subtitle: '副標補一個具體數字或情境。', ctaText: '立即開始', ctaHref: '/store', cta2Text: '看示範', cta2Href: '#video' },
      { kind: 'logos', title: '這些團隊正在使用', items: [{ name: 'A' }, { name: 'B' }, { name: 'C' }, { name: 'D' }, { name: 'E' }] },
      { kind: 'features', id: 'features', variant: 'icons', title: '三個核心賣點', columns: 3, items: [{ icon: '⚡', title: '快', text: '一句話' }, { icon: '🔒', title: '穩', text: '一句話' }, { icon: '💡', title: '省', text: '一句話' }] },
      { kind: 'split', title: '好處一', text: '把功能翻譯成使用者得到的結果。', imageSide: 'right' },
      { kind: 'split', title: '好處二', text: '再一個結果，換邊放圖。', imageSide: 'left' },
      { kind: 'testimonials', variant: 'quotes', title: '使用者怎麼說', items: [{ quote: '一句原話。', name: '使用者', role: '職稱' }, { quote: '一句原話。', name: '使用者', role: '職稱' }] },
      { kind: 'pricing', id: 'pricing', title: '方案', plans: [{ name: '入門', price: 'NT$0', period: '/月', features: ['功能 1', '功能 2'], ctaText: '免費開始', ctaHref: '/register' }, { name: '專業', price: 'NT$990', period: '/月', features: ['入門全部', '功能 3', '功能 4'], ctaText: '選擇專業', ctaHref: '/store', highlight: true }, { name: '企業', price: '洽談', features: ['專業全部', '專屬窗口'], ctaText: '聯絡我們', ctaHref: '/p/contact' }] },
      { kind: 'faq', id: 'faq', title: '常見問題', items: [{ q: '可以免費試用嗎？', a: '可以，入門方案永久免費。' }, { q: '怎麼付款？', a: '信用卡、ATM、超商代碼。' }, { q: '可以隨時取消嗎？', a: '可以，當期結束後生效。' }] },
      { kind: 'cta', variant: 'card', title: '今天就開始', text: '三分鐘完成設定。', buttonText: '立即開始', buttonHref: '/store' },
    ],
    pages: [PAGES.contact()],
  },
  {
    id: 'image-tech-gradient', category: 'image', name: '科技公司', style: '漸層 · 深色', tagline: '深色底＋漸層主視覺，適合軟體、AI、新創', tags: ['科技', '新創', 'AI'], source: 'Wix 科技公司 (深色)／AI 公司骨架',
    theme: { mode: 'dark', accent: '#7c3aed', accent2: '#06b6d4', font: 'display', radius: 'xl', header: 'transparent', footer: 'columns' },
    menu: { header: nav([{ label: '產品', href: '/p/services' }, { label: '部落格', href: '/blog' }]), footer: MENU.footerBasic },
    home: [
      { kind: 'hero', variant: 'center', kicker: 'AI-POWERED', title: '讓每個團隊都有自己的智慧引擎', subtitle: '一句話說明產品做什麼。', ctaText: '預約展示', ctaHref: '/p/contact', cta2Text: '看產品', cta2Href: '/p/services', tone: 'accent' },
      { kind: 'logos', items: [{ name: 'A' }, { name: 'B' }, { name: 'C' }, { name: 'D' }, { name: 'E' }, { name: 'F' }] },
      { kind: 'features', variant: 'grid', title: '平台能力', columns: 3, items: [{ icon: '🧠', title: '能力一', text: '一句話' }, { icon: '🔗', title: '能力二', text: '一句話' }, { icon: '📊', title: '能力三', text: '一句話' }, { icon: '🛡️', title: '能力四', text: '一句話' }, { icon: '⚙️', title: '能力五', text: '一句話' }, { icon: '🌐', title: '能力六', text: '一句話' }] },
      { kind: 'split', title: '用一個場景說明', text: '從問題到結果，三句話。', imageSide: 'right' },
      { kind: 'stats', variant: 'row', items: [{ value: '99.9%', label: '可用率' }, { value: '<50ms', label: '回應' }, { value: '10k+', label: '使用者' }] },
      { kind: 'split', title: '安全與合規', text: '資料在哪裡、誰能看、怎麼備份。', imageSide: 'left', bullets: ['加密傳輸與儲存', '權限分級', '每日備份'] },
      { kind: 'cta', variant: 'band', title: '預約 30 分鐘展示', buttonText: '預約', buttonHref: '/p/contact' },
    ],
    pages: [about('關於團隊'), { slug: 'services', title: '產品', sections: [{ kind: 'hero', variant: 'center', title: '產品', compact: true }, { kind: 'features', variant: 'list', items: [{ title: '模組一', text: '一句話' }, { title: '模組二', text: '一句話' }, { title: '模組三', text: '一句話' }] }, { kind: 'pricing', title: '方案', plans: [{ name: '團隊', price: 'NT$2,900', period: '/月', features: ['5 位使用者', '基本模組'], ctaText: '開始', ctaHref: '/p/contact' }, { name: '企業', price: '洽談', features: ['不限使用者', '全部模組', 'SLA'], ctaText: '聯絡我們', ctaHref: '/p/contact', highlight: true }] }] }, PAGES.contact()],
  },
  {
    id: 'image-scroll-story', category: 'image', name: '長捲動故事站', style: '大字', tagline: '宣言、理念三段、七步流程、作品、FAQ，一頁講完一家公司', tags: ['設計公司', '單頁', '故事'], source: '參考站山川久也骨架',
    theme: { mode: 'light', accent: '#111827', font: 'display', radius: 'none', header: 'centered', footer: 'simple', heading: 'display' },
    menu: { header: [{ label: '理念', href: '/#why' }, { label: '流程', href: '/#process' }, { label: '作品', href: '/p/works' }, { label: '知識庫', href: '/blog' }, { label: '聯絡', href: '/p/contact' }], footer: MENU.footerBasic },
    home: [
      { kind: 'hero', variant: 'editorial', kicker: 'UNLIMITED', title: '無設限，\n與你一起做出經典。', subtitle: '一句話。', ctaText: '看作品', ctaHref: '/p/works' },
      { kind: 'features', id: 'why', variant: 'numbered', title: '我們相信', columns: 3, items: [{ code: '01', title: '好看的東西，時間會證明', text: '兩句話。' }, { code: '02', title: '想吃牛排，就自己養牛', text: '兩句話。' }, { code: '03', title: '設計是門面，後端是底氣', text: '兩句話。' }] },
      { kind: 'steps', id: 'process', variant: 'timeline', title: '七步成站', items: [{ title: '訪談' }, { title: '提案' }, { title: '視覺' }, { title: '前端' }, { title: '後端' }, { title: '測試' }, { title: '上線' }] },
      { kind: 'gallery', variant: 'grid', title: '作品一覽', columns: 4, items: [] },
      { kind: 'logos', title: '久，是名字，也是答應過的事', items: [{ name: '客戶' }, { name: '客戶' }, { name: '客戶' }, { name: '客戶' }, { name: '客戶' }, { name: '客戶' }, { name: '客戶' }, { name: '客戶' }] },
      { kind: 'posts', variant: 'list', title: '知識庫', limit: 5 },
      { kind: 'faq', title: '做網站像抹茶，苦多過甜', items: [{ q: '費用？', a: '依規模，一次報清。' }, { q: '時程？', a: '八到十二週。' }, { q: '上線後？', a: '才剛開始，維護方案見說明。' }] },
    ],
    pages: [{ slug: 'works', title: '作品', sections: [{ kind: 'hero', variant: 'center', title: '作品', compact: true }, { kind: 'gallery', variant: 'masonry', columns: 3, items: [] }] }, about('關於'), PAGES.contact()],
  },
  {
    id: 'image-agency-fresh', category: 'image', name: '行銷代理商', style: '亮眼', tagline: '服務磚、見證牆、文章，適合行銷、廣告、社群代理商', tags: ['行銷', '廣告', '社群'], source: 'Wix 數位行銷代理商骨架',
    theme: { mode: 'light', accent: '#f97316', accent2: '#ec4899', font: 'rounded', radius: 'xl', header: 'solid', footer: 'columns', heading: 'bold' },
    menu: { header: nav([{ label: '服務', href: '/#services' }, { label: '案例', href: '/p/cases' }, { label: '部落格', href: '/blog' }]), footer: MENU.footerBasic },
    home: [
      { kind: 'hero', variant: 'left', kicker: '成長夥伴', title: '讓對的人，在對的時間看見你', subtitle: '一句話說明你怎麼帶來成長。', ctaText: '免費健檢', ctaHref: '/p/contact', imageUrl: '' },
      { kind: 'categories', id: 'services', variant: 'tiles', title: '服務', columns: 4, items: [{ icon: '📣', title: '廣告投放', href: '/p/services' }, { icon: '📱', title: '社群經營', href: '/p/services' }, { icon: '🎬', title: '影音製作', href: '/p/services' }, { icon: '🔍', title: 'SEO', href: '/p/services' }] },
      { kind: 'stats', variant: 'cards', items: [{ value: '3.2x', label: '平均 ROAS' }, { value: '120+', label: '品牌' }, { value: '8', label: '年' }] },
      { kind: 'testimonials', variant: 'wall', title: '客戶怎麼說', items: [{ quote: '一句原話。', name: '客戶', role: '電商' }, { quote: '一句原話。', name: '客戶', role: '餐飲' }, { quote: '一句原話。', name: '客戶', role: '教育' }, { quote: '一句原話。', name: '客戶', role: '美妝' }, { quote: '一句原話。', name: '客戶', role: '零售' }, { quote: '一句原話。', name: '客戶', role: '服務' }] },
      { kind: 'posts', variant: 'grid', title: '行銷筆記', limit: 3 },
      { kind: 'cta', variant: 'band', title: '先做一次免費健檢', buttonText: '預約', buttonHref: '/p/contact' },
    ],
    pages: [{ slug: 'services', title: '服務', sections: [{ kind: 'hero', variant: 'center', title: '服務', compact: true }, { kind: 'features', variant: 'list', items: [{ icon: '📣', title: '廣告投放', text: '一句話' }, { icon: '📱', title: '社群經營', text: '一句話' }, { icon: '🎬', title: '影音製作', text: '一句話' }, { icon: '🔍', title: 'SEO', text: '一句話' }] }] }, { slug: 'cases', title: '案例', sections: [{ kind: 'hero', variant: 'center', title: '案例', compact: true }, { kind: 'gallery', variant: 'grid', columns: 3, items: [] }] }, about(), PAGES.contact()],
  },
  {
    id: 'image-realestate', category: 'image', name: '房地產登陸頁', style: '時尚', tagline: '滿版建案主視覺、特色、圖庫、數字、地圖與預約', tags: ['建案', '房仲', '登陸頁'], source: 'Wix 房地產登陸頁面骨架',
    theme: { mode: 'light', accent: '#8b5e34', font: 'serif', radius: 'sm', header: 'transparent', footer: 'minimal' },
    menu: { header: [{ label: '特色', href: '/#features' }, { label: '格局', href: '/#gallery' }, { label: '位置', href: '/#map' }, { label: '預約賞屋', href: '/p/contact' }], footer: MENU.footerBasic },
    home: [
      { kind: 'hero', variant: 'cover', kicker: '限量 36 戶', title: '住進城市裡的一片綠', subtitle: '一句話定位。', ctaText: '預約賞屋', ctaHref: '/p/contact', tone: 'image' },
      { kind: 'features', id: 'features', variant: 'icons', title: '建案特色', columns: 4, items: [{ icon: '🌳', title: '綠地', text: '一句話' }, { icon: '🚇', title: '交通', text: '一句話' }, { icon: '🏫', title: '學區', text: '一句話' }, { icon: '🏛️', title: '建材', text: '一句話' }] },
      { kind: 'gallery', id: 'gallery', variant: 'grid', title: '格局與實景', columns: 3, items: [] },
      { kind: 'stats', variant: 'row', items: [{ value: '28-42', label: '坪' }, { value: '2-3', label: '房' }, { value: '2027', label: '完工' }] },
      { kind: 'contact', id: 'map', variant: 'map', title: '位置', mapEmbedUrl: '', items: [{ icon: '📍', label: '接待中心', value: '地址', href: '' }, { icon: '📞', label: '預約專線', value: '02-0000-0000', href: 'tel:+886200000000' }] },
      { kind: 'cta', variant: 'band', title: '預約賞屋', buttonText: '立即預約', buttonHref: '/p/contact' },
    ],
    pages: [PAGES.contact()],
  },
  {
    id: 'image-startup-app', category: 'image', name: '應用程式登陸', style: '活力', tagline: '影片主視覺、三步驟、方案、FAQ，適合 App／訂閱服務', tags: ['App', '訂閱', '登陸頁'], source: 'Wix 應用程式登陸頁骨架',
    theme: { mode: 'light', accent: '#16a34a', font: 'rounded', radius: 'full', header: 'minimal', footer: 'minimal', heading: 'bold' },
    menu: { header: [{ label: '功能', href: '/#features' }, { label: '怎麼用', href: '/#steps' }, { label: '方案', href: '/#pricing' }], footer: MENU.footerBasic },
    home: [
      { kind: 'hero', variant: 'split', title: '把每天要做的事，交給一個 App', subtitle: '一句話。', ctaText: '免費下載', ctaHref: '#', cta2Text: '看介紹', cta2Href: '#features', videoUrl: '' },
      { kind: 'features', id: 'features', variant: 'icons', columns: 3, items: [{ icon: '⏱️', title: '功能一', text: '一句話' }, { icon: '🔔', title: '功能二', text: '一句話' }, { icon: '☁️', title: '功能三', text: '一句話' }] },
      { kind: 'steps', id: 'steps', variant: 'cards', title: '三步開始', items: [{ title: '下載', text: '一句話' }, { title: '設定', text: '一句話' }, { title: '使用', text: '一句話' }] },
      { kind: 'pricing', id: 'pricing', plans: [{ name: '免費', price: 'NT$0', features: ['基本功能'], ctaText: '開始', ctaHref: '/register' }, { name: 'Pro', price: 'NT$150', period: '/月', features: ['全部功能', '雲端同步'], ctaText: '升級', ctaHref: '/store', highlight: true }] },
      { kind: 'faq', items: [{ q: '支援哪些裝置？', a: 'iOS、Android、網頁。' }, { q: '資料安全嗎？', a: '加密儲存並每日備份。' }] },
      { kind: 'cta', variant: 'card', title: '現在就下載', buttonText: '免費下載', buttonHref: '#' },
    ],
    pages: [PAGES.contact()],
  },
  {
    id: 'image-manufacturing', category: 'image', name: '製造業 B2B', style: '專業', tagline: '產品分類、產能數字、工廠介紹、認證客戶牆與詢價', tags: ['製造', 'B2B', '外銷'], source: 'Wix 工業類骨架',
    theme: { mode: 'light', accent: '#1e40af', font: 'sans', radius: 'sm', header: 'solid', footer: 'columns' },
    menu: { header: nav([{ label: '產品', href: '/store' }, { label: '產能與品質', href: '/p/services' }]), footer: MENU.footerBasic },
    home: [
      { kind: 'hero', variant: 'left', kicker: 'SINCE 1988', title: '三十年精密製造，交期與品質同時到位', subtitle: '一句話說明主力產品與市場。', ctaText: '產品型錄', ctaHref: '/store', cta2Text: '詢價', cta2Href: '/p/contact' },
      { kind: 'categories', variant: 'tiles', title: '產品線', columns: 4, items: [{ title: '產品線 A', href: '/store' }, { title: '產品線 B', href: '/store' }, { title: '產品線 C', href: '/store' }, { title: '客製', href: '/p/contact' }] },
      { kind: 'stats', variant: 'row', items: [{ value: '3', label: '座工廠' }, { value: '500 萬', label: '年產能' }, { value: 'ISO 9001', label: '認證' }, { value: '30+', label: '出口國' }] },
      { kind: 'split', title: '產能與品質', text: '設備、檢驗、交期管理各一段。', imageSide: 'right', bullets: ['全製程檢驗', '客製打樣 7 天', '準時交貨率 99%'] },
      { kind: 'logos', title: '合作客戶', items: [{ name: 'A' }, { name: 'B' }, { name: 'C' }, { name: 'D' }, { name: 'E' }, { name: 'F' }] },
      { kind: 'contact', variant: 'columns', title: '詢價與聯絡', items: [{ icon: '✉️', label: '業務信箱', value: 'sales@example.com', href: 'mailto:sales@example.com' }, { icon: '📞', label: '電話', value: '02-0000-0000', href: 'tel:+886200000000' }, { icon: '📍', label: '工廠', value: '地址', href: '' }] },
    ],
    pages: [{ slug: 'services', title: '產能與品質', sections: [{ kind: 'hero', variant: 'center', title: '產能與品質', compact: true }, { kind: 'features', variant: 'list', items: [{ title: '設備', text: '一句話' }, { title: '檢驗', text: '一句話' }, { title: '交期', text: '一句話' }] }, { kind: 'gallery', variant: 'grid', columns: 3, items: [] }] }, about('公司簡介'), PAGES.contact()],
  },
  {
    id: 'image-minimal-onepage', category: 'image', name: '極簡單頁', style: '留白', tagline: '一段介紹、一張圖、三項服務、聯絡方式，十分鐘上線', tags: ['極簡', '單頁', '快速'], source: 'Wix 單頁面骨架',
    theme: { mode: 'light', accent: '#171717', font: 'serif', radius: 'none', header: 'centered', footer: 'minimal', container: 'narrow' },
    menu: { header: [{ label: '介紹', href: '/#about' }, { label: '服務', href: '/#services' }, { label: '聯絡', href: '/#contact' }], footer: [] },
    home: [
      { kind: 'hero', variant: 'center', title: '你的名字或公司', subtitle: '一句話。', compact: true },
      { kind: 'split', id: 'about', title: '介紹', text: '兩三段。', imageSide: 'left' },
      { kind: 'features', id: 'services', variant: 'list', title: '服務', items: [{ title: '服務一', text: '一句話' }, { title: '服務二', text: '一句話' }, { title: '服務三', text: '一句話' }] },
      { kind: 'contact', id: 'contact', variant: 'columns', title: '聯絡', items: [{ icon: '✉️', label: 'Email', value: 'hello@example.com', href: 'mailto:hello@example.com' }, { icon: '📞', label: '電話', value: '02-0000-0000', href: 'tel:+886200000000' }] },
    ],
    pages: [PAGES.contact()],
  },
];
