#!/usr/bin/env node
/**
 * Prisma 指令包裝：一份模型、兩種資料庫。
 *   node packages/db/scripts/prisma.mjs generate        產生 postgres 與 sqlite 兩個 client
 *   node packages/db/scripts/prisma.mjs validate        驗證兩份 schema
 *   node packages/db/scripts/prisma.mjs migrate         依 DATABASE_URL 對正確的 schema 跑 migrate deploy
 *   node packages/db/scripts/prisma.mjs diff-sqlite <name>   由 postgres 版重產 sqlite schema，並產生 sqlite 新 migration（開發者改模型後執行）
 */
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../../..');
const PG = resolve(root, 'apps/api/prisma/schema.prisma');
const SQ = resolve(root, 'packages/db/sqlite/schema.prisma');
const SQ_MIGRATIONS = resolve(root, 'packages/db/sqlite/migrations');
const cmd = process.argv[2] ?? 'help';
const url = process.env.DATABASE_URL ?? '';
const isSqlite = /^file:/i.test(url);

function run(args, env = {}) {
  const r = spawnSync(process.platform === 'win32' ? 'npx.cmd' : 'npx', ['prisma', ...args], { stdio: 'inherit', cwd: root, env: { ...process.env, ...env }, shell: process.platform === 'win32' });
  if (r.status !== 0) process.exit(r.status ?? 1);
}
function gen() {
  run(['generate', '--schema', PG]);
  run(['generate', '--schema', SQ]);
}
switch (cmd) {
  case 'generate':
    gen();
    break;
  case 'validate':
    run(['validate', '--schema', PG]);
    run(['validate', '--schema', SQ]);
    break;
  case 'migrate':
    if (!url) {
      console.error('DATABASE_URL is required');
      process.exit(1);
    }
    run(['migrate', 'deploy', '--schema', isSqlite ? SQ : PG]);
    break;
  case 'diff-sqlite': {
    const name = process.argv[3] ?? 'change';
    const r = spawnSync(process.execPath, [resolve(here, 'gen-sqlite-schema.mjs')], { stdio: 'inherit' });
    if (r.status !== 0) process.exit(r.status ?? 1);
    mkdirSync(SQ_MIGRATIONS, { recursive: true });
    const stamp = new Date().toISOString().replace(/[-:TZ.]/g, '').slice(0, 14);
    const dir = resolve(SQ_MIGRATIONS, `${stamp}_${name}`);
    const hasPrev = existsSync(SQ_MIGRATIONS) && readdirSync(SQ_MIGRATIONS).some((d) => /^\d{14}_/.test(d));
    const shadow = resolve(root, 'packages/db/sqlite/.shadow.db');
    const args = ['migrate', 'diff', ...(hasPrev ? ['--from-migrations', SQ_MIGRATIONS, '--shadow-database-url', `file:${shadow}`] : ['--from-empty']), '--to-schema-datamodel', SQ, '--script'];
    const out = spawnSync(process.platform === 'win32' ? 'npx.cmd' : 'npx', ['prisma', ...args], { cwd: root, encoding: 'utf8', shell: process.platform === 'win32' });
    if (out.status !== 0) {
      console.error(out.stderr || out.stdout);
      process.exit(out.status ?? 1);
    }
    const sql = out.stdout.trim();
    if (!sql || /^-- This is an empty migration/.test(sql)) {
      console.log('sqlite schema 無變更，不產生 migration');
      break;
    }
    mkdirSync(dir, { recursive: true });
    writeFileSync(resolve(dir, 'migration.sql'), sql + '\n');
    if (!existsSync(resolve(SQ_MIGRATIONS, 'migration_lock.toml'))) writeFileSync(resolve(SQ_MIGRATIONS, 'migration_lock.toml'), '# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "sqlite"\n');
    console.log(`sqlite migration → ${dir}`);
    break;
  }
  default:
    console.log('usage: prisma.mjs generate|validate|migrate|diff-sqlite <name>');
}
