#!/usr/bin/env node
/**
 * Prisma 指令包裝：一份模型、三種資料庫（postgresql／sqlite／mysql）。
 *   node packages/db/scripts/prisma.mjs generate        產生 postgres、sqlite、mysql 三個 client
 *   node packages/db/scripts/prisma.mjs validate        驗證三份 schema
 *   node packages/db/scripts/prisma.mjs migrate         依 DATABASE_URL 協定對正確的 schema 跑 migrate deploy
 *   node packages/db/scripts/prisma.mjs diff-sqlite <name>   由 postgres 版重產 sqlite schema，並產生 sqlite 新 migration（開發者改模型後執行）
 *   node packages/db/scripts/prisma.mjs diff-mysql <name>    同上 mysql 版；第二次起需要 MYSQL_SHADOW_URL（一個可清空的 MySQL 庫）算差異
 */
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../../..');
const PG = resolve(root, 'apps/api/prisma/schema.prisma');
const SQ = resolve(root, 'packages/db/sqlite/schema.prisma');
const SQ_MIGRATIONS = resolve(root, 'packages/db/sqlite/migrations');
const MY = resolve(root, 'packages/db/mysql/schema.prisma');
const MY_MIGRATIONS = resolve(root, 'packages/db/mysql/migrations');
const cmd = process.argv[2] ?? 'help';
const url = process.env.DATABASE_URL ?? '';
const isSqlite = /^file:/i.test(url);
const isMysql = /^mysql:/i.test(url);

function run(args, env = {}) {
  const r = spawnSync(process.platform === 'win32' ? 'npx.cmd' : 'npx', ['prisma', ...args], { stdio: 'inherit', cwd: root, env: { ...process.env, ...env }, shell: process.platform === 'win32' });
  if (r.status !== 0) process.exit(r.status ?? 1);
}
// validate／generate 會檢查 datasource URL 的協定：對「另一種」schema 執行時給一個同協定的假 URL（不需連線）
const PG_ENV = isSqlite || isMysql || !url ? { DATABASE_URL: 'postgresql://sitekit:sitekit@localhost:5432/sitekit' } : {};
const SQ_ENV = !isSqlite ? { DATABASE_URL: 'file:./.validate.db' } : {};
const MY_ENV = !isMysql ? { DATABASE_URL: 'mysql://sitekit:sitekit@localhost:3306/sitekit' } : {};
function gen() {
  run(['generate', '--schema', PG], PG_ENV);
  run(['generate', '--schema', SQ], SQ_ENV);
  run(['generate', '--schema', MY], MY_ENV);
}
switch (cmd) {
  case 'generate':
    gen();
    break;
  case 'validate':
    run(['validate', '--schema', PG], PG_ENV);
    run(['validate', '--schema', SQ], SQ_ENV);
    run(['validate', '--schema', MY], MY_ENV);
    break;
  case 'migrate':
    if (!url) {
      console.error('DATABASE_URL is required');
      process.exit(1);
    }
    run(['migrate', 'deploy', '--schema', isSqlite ? SQ : isMysql ? MY : PG]);
    break;
  case 'diff-sqlite': {
    const name = process.argv[3] ?? 'change';
    const r = spawnSync(process.execPath, [resolve(here, 'gen-sqlite-schema.mjs')], { stdio: 'inherit' });
    if (r.status !== 0) process.exit(r.status ?? 1);
    mkdirSync(SQ_MIGRATIONS, { recursive: true });
    const stamp = new Date().toISOString().replace(/[-:TZ.]/g, '').slice(0, 14);
    const dir = resolve(SQ_MIGRATIONS, `${stamp}_${name}`);
    const hasPrev = existsSync(SQ_MIGRATIONS) && readdirSync(SQ_MIGRATIONS).some((d) => /^\d{14}_/.test(d));
    const shadow = resolve(root, 'packages/db/sqlite/.shadow.db');
    const args = ['migrate', 'diff', ...(hasPrev ? ['--from-migrations', SQ_MIGRATIONS, '--shadow-database-url', `file:${shadow}`] : ['--from-empty']), '--to-schema-datamodel', SQ, '--script'];
    const out = spawnSync(process.platform === 'win32' ? 'npx.cmd' : 'npx', ['prisma', ...args], { cwd: root, encoding: 'utf8', shell: process.platform === 'win32' });
    if (out.status !== 0) {
      console.error(out.stderr || out.stdout);
      process.exit(out.status ?? 1);
    }
    const sql = out.stdout.trim();
    if (!sql || /^-- This is an empty migration/.test(sql)) {
      console.log('sqlite schema 無變更，不產生 migration');
      break;
    }
    mkdirSync(dir, { recursive: true });
    writeFileSync(resolve(dir, 'migration.sql'), sql + '\n');
    if (!existsSync(resolve(SQ_MIGRATIONS, 'migration_lock.toml'))) writeFileSync(resolve(SQ_MIGRATIONS, 'migration_lock.toml'), '# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "sqlite"\n');
    console.log(`sqlite migration → ${dir}`);
    break;
  }
  case 'diff-mysql': {
    const name = process.argv[3] ?? 'change';
    const r = spawnSync(process.execPath, [resolve(here, 'gen-mysql-schema.mjs')], { stdio: 'inherit' });
    if (r.status !== 0) process.exit(r.status ?? 1);
    mkdirSync(MY_MIGRATIONS, { recursive: true });
    const stamp = new Date().toISOString().replace(/[-:TZ.]/g, '').slice(0, 14);
    const dir = resolve(MY_MIGRATIONS, `${stamp}_${name}`);
    const hasPrev = existsSync(MY_MIGRATIONS) && readdirSync(MY_MIGRATIONS).some((d) => /^\d{14}_/.test(d));
    if (hasPrev && !process.env.MYSQL_SHADOW_URL) {
      console.error('已有 mysql migration：算差異需要 MYSQL_SHADOW_URL（例：mysql://root:root@localhost:3306/sitekit_shadow，會被清空）');
      process.exit(1);
    }
    const args = ['migrate', 'diff', ...(hasPrev ? ['--from-migrations', MY_MIGRATIONS, '--shadow-database-url', process.env.MYSQL_SHADOW_URL] : ['--from-empty']), '--to-schema-datamodel', MY, '--script'];
    const out = spawnSync(process.platform === 'win32' ? 'npx.cmd' : 'npx', ['prisma', ...args], { cwd: root, encoding: 'utf8', shell: process.platform === 'win32', env: { ...process.env, ...MY_ENV } });
    if (out.status !== 0) {
      console.error(out.stderr || out.stdout);
      process.exit(out.status ?? 1);
    }
    const sql = out.stdout.trim();
    if (!sql || /^-- This is an empty migration/.test(sql)) {
      console.log('mysql schema 無變更，不產生 migration');
      break;
    }
    mkdirSync(dir, { recursive: true });
    writeFileSync(resolve(dir, 'migration.sql'), sql + '\n');
    if (!existsSync(resolve(MY_MIGRATIONS, 'migration_lock.toml'))) writeFileSync(resolve(MY_MIGRATIONS, 'migration_lock.toml'), '# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "mysql"\n');
    console.log(`mysql migration → ${dir}`);
    break;
  }
  default:
    console.log('usage: prisma.mjs generate|validate|migrate|diff-sqlite <name>|diff-mysql <name>');
}
